all: libs
	
clean:
	cd data_processing; make clean
	cd multiply; make clean
	cd single_data_transfer; make clean
	cd branch; make clean
	cd symbol_table; make clean
	cd special; make clean
libs: 
	cd data_processing; make
	cd multiply; make
	cd single_data_transfer; make
	cd branch; make
	cd symbol_table; make
	cd special; make
