#!/bin/bash
export SSFLAGS="-ruu:size 16 -lsq:size 16 -res:fpalu 1 -res:fpmult 1 -decode:width 4 -issue:width 4 -res:ialu 3 -cache:dl1 dl1:128:32:1:l -cache:dl2 ul2:128:64:1:l -bpred comb -bpred:comb 128 -bpred:ras 8 -bpred:btb 256 2 -tlb:itlb itlb:16:4096:1:l -tlb:dtlb dtlb:16:4096:1:l -cache:il2 dl2"
