#!/bin/bash

for ruu_size in 8 16 32 64 128 256
do
  for lsq_size in 8 16 32 64 128 256
  do
    echo -n "D1_cache_size,128,D1_cache_linesize,32,bpred,bimod,ruu_size,$ruu_size,lsq_size,$lsq_size"
    export SSFLAGS="-ruu:size $ruu_size -lsq:size $lsq_size"
    ./run-wattch 2>&1 | ./scripts/tabulate
  done
done
