#!/bin/bash

# Usage: varycachesize 256 8192 for powers of two from 256 to 8192 inclusive
#
if [ -z $1 ];
then
  echo "Usage: ./scripts/$0 <min-cache-size> <max-cache-size>"
else
  for ((cache_size=$1; cache_size <= $2; cache_size *= 2))
  do
    echo -n "D1_cache_size,$cache_size,D1_cache_linesize,32,bpred,bimod,ruu_size,16,lsq_size,8"
    export SSFLAGS="-cache:dl1 dl1:$cache_size:32:1:l"
    ./run-wattch 2>&1 | ./scripts/tabulate
  done
fi

