#!/bin/bash

# Usage: varycachesize 256 8192 for powers of two from 256 to 8192 inclusive
#
for cache_size in 64
do
  for cache_line_size in 64
  do
    for associativity in 1 2 4 8
    do
        for replacement_strategy in l f r
        do
          echo -n "I1_cache_size,$cache_size,I1_cache_linesize,$cache_line_size,replacement_strategy, $replacement_strategy, bpred,bimod,ruu_size,16,lsq_size,8"
          export SSFLAGS="-cache:il1 il1:$cache_size:$cache_line_size:$associativity:$replacement_strategy -ruu:size 16 -lsq:size 8 -res:fpalu 1 -res:fpmult 1 -decode:width 2 -issue:width 2 -commit:width 8 -res:ialu 2 -cache:dl1 dl1:128:32:1:l -cache:dl2 ul2:128:64:2:l -bpred comb -bpred:comb 128 -bpred:ras 8 -bpred:btb 256 2 -tlb:itlb itlb:16:4096:1:l -tlb:dtlb dtlb:16:4096:1:l -cache:il2 dl2"
          ./run-wattch 2>&1 | ./scripts/tabulate
        done
    done
  done
done

